### ISSUE TITLE
v6 jamming problems

### ISSUE THREAD

**Issue by diegotrap** [Bitfab-io/farmops-issues#2]
The E3D v6 hotend+Titan extruder system in the Bitfab Core has been experiencing jamming issues. Documenting all changes and troubleshooting with this hotend.

**Problem description**
Jams appear suddenly during printing, not gradually, grinding starts to happen in the extruder. They can be cleared by extracting the filament and then extruding manually, so they shouldn't be due to nozzle clogging. 

**Previously done**

* Retraction set to 0.5mm, retraction speed 30mm/s
* Currently cold tightening the nozzle at 3Nm
* Assembly error: PTFE tube too short. Now it's the correct length.
* Assembly error: Heatbreak loose, without thermal compound. Now we use thermal compound and tighten the heatbreak into the heatsink with a 1.2Nm torque.
* Bad first layers. We printed without first layer supervision, resulting in too low first layers that may cause jamming in the first or subsequent layers.
* Changed nozzle once, the whole v6 has less than one or two hundred hours.
* Changed filament (Smartmaterials to Fillamentum), did one test, still jamming.

**Testing now, 19 April 2018**

* Titan lid was cracked, probably not affecting much, replaced
* Idler tension may vary between tests, now its constant (using one M4 bolt and two nuts, not adjustable)
* Replaced hotend fan (0.10A, 30x30mm original fan) and cable.

**Other possible causes**

* Hot heatbreak due to too many retractions?
* Heat coming out of the bed getting into the hotend fan and into the heatsink (heat bed 50ºC)?
* Dust in the filament?
* Printing Smartmaterials too cold? (currently 220ºC, recommended temperature 220+-20ºC)
* Titan extruder misalignment?

**Other notes:**

* Don't use with materials other than PLA for the duration of this test
* Test gcode, attached (as a txt). Now it is hard to print a couple of them without having issues.

[marco_test_v6.txt](https://github.com/Bitfab-io/farmops-issues/files/1927866/marco_test_v6.txt)

**Comment by diegotrap** [comment]
**This issue has an independent thread (already solved): https://github.com/Bitfab-io/farmops-issues/issues/3**

Printer stops mid print with serial connection error. Have just happened and happened once before after changing the USB cable powering the Raspberry Pi.

No thermal runaway error. No signs of underextrusion, jamming... Printed half a test model before this error, test was OK.

I have switched back to the old USB cable.

Error log:

> 2018-04-19 16:45:49,168 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2417, in _readline
    ret = self._serial.readline()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 4334, in readline
    c = self.read(1)
  File "build/bdist.linux-armv7l/egg/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2018-04-19 16:45:49,189 - octoprint.util.comm - ERROR - Please see https://faq.octoprint.org/serialerror for possible reasons of this.
2018-04-19 16:45:49,204 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2417)"

**Comment by diegotrap** [comment]
Problem seems solved after replacing fan and cable as described in the opening post, issue will be closed.

We have printed 52 hours of the `marco_test_v6.gcode` file, which was causing issues with the previous setup.


**Solution: replacing hotend fan and hotend fan cable.**
**M78: 259h**
>Recv: Stats: Prints: 113, Finished: 101, Failed: 12
>Recv: Stats: Total time: 10d 19h 15m 40s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 773.52m

**Comment by diegotrap** [comment]
New jam with other gcode `Heatsink_cutaway_heatbreaker`. Settings seem OK in the gcode (retraction, speeds...). Differences: printing at 210ºC instead of 220ºC.

We will try to print some more `marco_test_v6.txt` files to see if the problem is related to the part or the printer.

**M78: 279h (the hotend printed for 72h without issues up to this problem)**

>Recv: Stats: Prints: 118, Finished: 105, Failed: 13
>Recv: Stats: Total time: 11d 14h 32m 23s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 832.84m

[Heatsink_cutaway_heatbreaker.txt](https://github.com/Bitfab-io/farmops-issues/files/1951001/Heatsink_cutaway_heatbreaker.txt)

**Comment by diegotrap** [comment]
Printing OK again. Last printed part showed signs of underextrusion, tried to unclog the nozzle with a needle.

**M78: 289h**

>Recv: Stats: Prints: 123, Finished: 109, Failed: 13
>Recv: Stats: Total time: 12d 0h 55m 57s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 871.72m

**Comment by diegotrap** [comment]
Jammed a second time printing Otto heads. It doesn't seem to be an obstructed nozzle but plastic sticking to the heatbreak again.

Actions taken:

* I will make sure we slice every part with the same profiles attached to this post. I think this job was sliced with Cura.
* Increased the retraction speed to 50mm/s

We need to get more test hours of this hotend to completely understand it.

**M78: 298h, less than 100 hours and already two jams and a clogged nozzle :(**
>Send: M78
>Recv: Stats: Prints: 124, Finished: 111, Failed: 13
>Recv: Stats: Total time: 12d 10h 6m 37s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 897.82m
>Recv: ok

**Comment by diegotrap** [comment]
We are still using Slic3r, but we are using a slightly different profile with Slic3r Prusa Edition. Printer OK.

**M78: 306h**
>Send: M78
>Recv: Stats: Prints: 132, Finished: 119, Failed: 13
>Recv: Stats: Total time: 12d 18h 2m 47s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 928.71m

**Comment by diegotrap** [comment]
Complete and sudden jam mid print, complete blockage without signs of underextrusion prior to the issue.

Hotend also showed signs of partial obstruction after removing the filament. We passed the needle several times. This obstruction maybe a result of the blockage (hot plastic in the melt zone for many hours) or the cause of the problem.

Will repeat the same gcode.

**M78: 362h**

>Send: M78
>Recv: Stats: Prints: 151, Finished: 138, Failed: 13
>Recv: Stats: Total time: 15d 2h 14m 34s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 1136.49m

**Comment by diegotrap** [comment]
We have briefly changed material to ASA for a couple of hours, will clean the hotend well and use PLA again. 

>Send: M78
>Recv: Stats: Prints: 167, Finished: 154, Failed: 13
>Recv: Stats: Total time: 16d 6h 50m 8s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 1239.83m

**Comment by diegotrap** [comment]
We have to finish the test because we are going to change to a 0.8mm nozzle.

The extrusion seems much more stable with this settings than our previous setup (Titan and E3D lite6 hotend), therefore we will use v6 hotends from now on.

No need to change PTFE in about 300h, not as many obstructions as with a lite6. All retractions seem to be caused by heat creep or nozzle obstruction, so it can be solved by using the correct printing settings or the needle method.

Test time: 497h - 259h + 52h = 290h

>Send: M78
>Recv: Stats: Prints: 228, Finished: 211, Failed: 17
>Recv: Stats: Total time: 20d 17h 12m 32s, Longest job: 16h 16m 14s
>Recv: Stats: Filament used: 1594.23m
>Recv: ok
