### ISSUE TITLE
Lost connection with printer

### ISSUE THREAD

**Issue by diegotrap** [Bitfab-io/farmops-issues#3]
**Signs:**

* Printer stops mid print
* Not showing Thermal Runaway error:
* Octoprint error message: `ERROR - Unexpected error while reading from serial port, SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?, ERROR - Please see https://faq.octoprint.org/serialerror for possible reasons of this, INFO - Changing monitoring state from "Printing" to "Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)'`

**Cause**

* This error is triggered when Octoprint can't connect to the printer. The Raspberry Pi may be underpowered, the USB faulty, loose, unshielded... The Arduino can be checked too (last).
* **All the info:**: https://discourse.octoprint.org/t/octoprint-randomly-loses-connection-to-the-printer-with-a-serialexception/228

**Complete log**

> 2018-04-19 16:45:49,168 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2417, in _readline
    ret = self._serial.readline()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 4334, in readline
    c = self.read(1)
  File "build/bdist.linux-armv7l/egg/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2018-04-19 16:45:49,189 - octoprint.util.comm - ERROR - Please see https://faq.octoprint.org/serialerror for possible reasons of this.
2018-04-19 16:45:49,204 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2417)"

Happened in the first Bitfab Core, 19/04/2018 and previous days, after change in the Raspberry Pi powering USB. Switching back to the old cable.

**Comment by diegotrap** [comment]
Now 52 hours of printing without any problem, issue seems solved.

**Solution: replacing Raspberry power USB cable.**
**M78: 259h**
>Recv: Stats: Prints: 113, Finished: 101, Failed: 12
>Recv: Stats: Total time: 10d 19h 15m 40s, Longest job: 14h 30m 13s
>Recv: Stats: Filament used: 773.52m
